language: ruby
cache: bundler
notifications:
  email: false
rbenv:
- 2.5.3
before_install:
- gem install bundler
addons:
  postgresql: 9.6
  chrome: stable
dist: xenial
script:
- bundle exec rails db:{create,migrate} RAILS_ENV=test
- bundle exec rspec
deploy:
  provider: heroku
  api_key:
    secure: m6u432apH1T+7Z5AHAyymXxozKYphMgye+c9SFqR+MjL0/WHdWSFwruU3cpHtZ/b9R4tUp2U40TWLwWu3U9w2bfUIVfDLVcT2cDkzYNiZvRJvRSb9D67gIYmmZcvrT5jRWXQ5pYTc27s/PA+BBtzmjHNvavTaJeeNP96kbTO1uZJpyawIn5kf1b5UPSbn14vR2l5HiRB2RzSnzQBrdCOF9QKfK09MGePsbx2qVnoSYmPpeXsIfr0ivT3mTXQaGeOrLA9IjwFbo6BA6XC+CRMeA+ouw3KsfCvo7kXOi0yLIoIjVlpx38zcwCgCaoPsCcgUFN9V6zyMh4egBz/ERJCIQS4NUqwQPcXAj6Bc+ykIzFwPIAGr7TR8QvQ5ItGQ/gLFGkOy8GoFGIXU5Cd2oxJpwiJG1cda+jokLWatjafZYXFIoUoULHPYMc2BM0B65drIXb/+8XCNjM2oNCrRTvJq9w3GP6ei9j8WNSC/FvYEJIG6Q4bf/KA/RrHDT7IU6tnxrKUngxY6cGGGMkz9lTmzxnJIaBpyesAcfX2kqHm3rSayyOlahlyIhOK1SaZd9VVrj/S4xxt41qe5Ofi46Zv/G/JadFXs2smrpzO7RPk4zSeZmwGeElkKqUnyAGsD7TFIWbMAuAGKAkNzeekxRpsRJdCei8uLAfSnKYLONhAP+4=
  app: sweater-weather-rp
  on:
    repo: perryr16/sweater_weather
  run: rails db:migrate
  skip_cleanup: true
