version: 2.1
orbs:
  heroku: circleci/heroku@1.2.0
workflows:
  heroku_deploy:
    jobs:
      - build
      - heroku/deploy-via-git:
          app-name: sweater-weather-rp
          requires:
            - build
          filters:
            branches:
              only: sequential-branch-filter
jobs:
  build:
    working_directory: ~/sweater_weather
    docker:
      - image: circleci/ruby:2.5.3
        environment:
          PGHOST: 127.0.0.1
          RAILS_ENV: test
          PGUSER: root
      - image: circleci/postgres:9.5-alpine
        environment: 
          POSTGRES_USER: root
          POSTGRES_DB: sweater_weather_test
    steps:
      - checkout
      - run: gem install bundler
      - run: bundle install
      - run: 
          name: Set up DB
          command: |
            bundle exec rake db:create 
            bundle exec rake db:migrate
            bundle exec rspec
        
      # - run:
      #     name: Run tests
      #     command: rake