version: 2.1
orbs:
  heroku: circleci/heroku@1.2.0
workflows:
  heroku_deploy:
    jobs:
      - build
      - heroku/deploy-via-git:
          requires:
            - build
          filters:
            branches:
              only: sequential-branch-filter
jobs:
  build:
    docker:
      - image: circleci/ruby:2.5.3
      - image: circleci/postgres:9.4.12-alpine
    working_directory: ~/sweater_weather
    steps:
      - checkout
      - run: gem install bundler
      - run: bundle install
      - run: 
          name: Set up DB
          command: |
            bundle exec rake db:create 
            bundle exec rake db:migrate
        
      # - run:
      #     name: Run tests
      #     command: rake